# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(392, 284)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.edit_date = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.edit_date.setFont(font)
        self.edit_date.setWrapping(False)
        self.edit_date.setCalendarPopup(True)
        self.edit_date.setObjectName("edit_date")
        self.verticalLayout_2.addWidget(self.edit_date)
        self.btn_upload = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btn_upload.setFont(font)
        self.btn_upload.setObjectName("btn_upload")
        self.verticalLayout_2.addWidget(self.btn_upload)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_pick_template = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btn_pick_template.setFont(font)
        self.btn_pick_template.setObjectName("btn_pick_template")
        self.verticalLayout.addWidget(self.btn_pick_template)
        self.template_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.template_label.setFont(font)
        self.template_label.setObjectName("template_label")
        self.verticalLayout.addWidget(self.template_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.btn_pick_dir = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btn_pick_dir.setFont(font)
        self.btn_pick_dir.setObjectName("btn_pick_dir")
        self.verticalLayout_2.addWidget(self.btn_pick_dir)
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_2.addWidget(self.info_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_generate.sizePolicy().hasHeightForWidth())
        self.btn_generate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.btn_generate.setFont(font)
        self.btn_generate.setObjectName("btn_generate")
        self.verticalLayout_2.addWidget(self.btn_generate)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор служебок"))
        self.btn_upload.setText(_translate("MainWindow", "Загрузить данные"))
        self.btn_pick_template.setText(_translate("MainWindow", "Выбрать шаблон"))
        self.template_label.setText(_translate("MainWindow", "Шаблон не выбран"))
        self.btn_pick_dir.setText(_translate("MainWindow", "Выбор папки вывода"))
        self.info_label.setText(_translate("MainWindow", "Статус: готовность"))
        self.btn_generate.setText(_translate("MainWindow", "Генерировать"))
